### ISSUE TITLE
Usul todo: optimasi image docker

### ISSUE THREAD

**Issue by azophy** [jabardigitalservice/pikobar-labkes-satelit#139]
![2021-02-05-102342_1281x470_scrot](https://user-images.githubusercontent.com/2698551/106985790-a5d9b700-679c-11eb-8ac5-3ffb938b4d06.png)

jadi ada laporan kalau disk usage di server caprover sudah hampir penuh. setelah diselidiki ternyata bbrp image docker kita lumayan besar, salah satunya image dari frontent aplikasi labkes satelit. Sambil dicari solusi agar history image di caprovernya gak terlalu numpuk, bagusnya bisa di optimize ukuran dockernya agar tidak terlalu penuh. salah satunya adalah dengan penerapan strategi layering dockerfile nya. lebih dalamnya bisa diskusi2 nanti sama tim devops.

nuhun kawan2 :pray:

**Comment by ayocodingit** [comment]
Terimakasih kang masukannya . Btw ini hanya satelit frontend nya aja atau ada yang lainnya juga .

**Comment by ayocodingit** [comment]
![image](https://user-images.githubusercontent.com/41193120/107225685-ae0b4e00-6a4b-11eb-9f29-fa970c21b17a.png)
https://github.com/jabardigitalservice/pikobar-labkes-satelit/pull/140
